//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirefighterProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firefighters
    {
        public int FirefighterID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int FiretruckID { get; set; }
    
        public virtual Firetrucks Firetrucks { get; set; }
    }
}
