//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirefighterProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firetrucks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firetrucks()
        {
            this.Incidents = new HashSet<Incidents>();
        }
    
        public int FiretruckID { get; set; }
        public bool IsMondayShift { get; set; }
        public bool IsTuesdayShift { get; set; }
        public bool IsWednesdayShift { get; set; }
        public bool IsThursdayShift { get; set; }
        public bool IsFridayShift { get; set; }
        public bool IsSaturdayShift { get; set; }
        public bool IsSundayShift { get; set; }
    
        public virtual Firefighters Firefighters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidents> Incidents { get; set; }
    }
}
