//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirefighterProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirefighterDBEntities : DbContext
    {
        public FirefighterDBEntities()
            : base("name=FirefighterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firefighters> Firefighters { get; set; }
        public virtual DbSet<Firetrucks> Firetrucks { get; set; }
        public virtual DbSet<Incidents> Incidents { get; set; }
    }
}
