//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirefighterProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firefighters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firefighters()
        {
            this.Incidents = new HashSet<Incidents>();
        }
    
        public int FirefighterID { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<System.DateTime> ShiftStartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidents> Incidents { get; set; }
    }
}
