//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirefighterProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidents
    {
        public int IncidentID { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public Nullable<int> AssignedFirefighterID { get; set; }
        public Nullable<int> AssignedFiretruckID { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    
        public virtual Firefighters Firefighters { get; set; }
        public virtual Firetrucks Firetrucks { get; set; }
    }
}
