//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirefighterProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidents
    {
        public int IncidentID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Duration { get; set; }
        public decimal WaterUsed { get; set; }
        public int FiretruckID { get; set; }
    
        public virtual Firetrucks Firetrucks { get; set; }
    }
}
